@testset "Element" begin

@test Element(1) == Elements.H
@test Element(2) == Elements.He
@test Element(3) == Elements.Li
@test Element(4) == Elements.Be
@test Element(5) == Elements.B
@test Element(6) == Elements.C
@test Element(7) == Elements.N
@test Element(8) == Elements.O
@test Element(9) == Elements.F
@test Element(10) == Elements.Ne
@test Element(11) == Elements.Na
@test Element(12) == Elements.Mg
@test Element(13) == Elements.Al
@test Element(14) == Elements.Si
@test Element(15) == Elements.P
@test Element(16) == Elements.S
@test Element(17) == Elements.Cl
@test Element(18) == Elements.Ar
@test Element(19) == Elements.K
@test Element(20) == Elements.Ca
@test Element(21) == Elements.Sc
@test Element(22) == Elements.Ti
@test Element(23) == Elements.V
@test Element(24) == Elements.Cr
@test Element(25) == Elements.Mn
@test Element(26) == Elements.Fe
@test Element(27) == Elements.Co
@test Element(28) == Elements.Ni
@test Element(29) == Elements.Cu
@test Element(30) == Elements.Zn
@test Element(31) == Elements.Ga
@test Element(32) == Elements.Ge
@test Element(33) == Elements.As
@test Element(34) == Elements.Se
@test Element(35) == Elements.Br
@test Element(36) == Elements.Kr
@test Element(37) == Elements.Rb
@test Element(38) == Elements.Sr
@test Element(39) == Elements.Y
@test Element(40) == Elements.Zr
@test Element(41) == Elements.Nb
@test Element(42) == Elements.Mo
@test Element(43) == Elements.Tc
@test Element(44) == Elements.Ru
@test Element(45) == Elements.Rh
@test Element(46) == Elements.Pd
@test Element(47) == Elements.Ag
@test Element(48) == Elements.Cd
@test Element(49) == Elements.In
@test Element(50) == Elements.Sn
@test Element(51) == Elements.Sb
@test Element(52) == Elements.Te
@test Element(53) == Elements.I
@test Element(54) == Elements.Xe
@test Element(55) == Elements.Cs
@test Element(56) == Elements.Ba
@test Element(57) == Elements.La
@test Element(58) == Elements.Ce
@test Element(59) == Elements.Pr
@test Element(60) == Elements.Nd
@test Element(61) == Elements.Pm
@test Element(62) == Elements.Sm
@test Element(63) == Elements.Eu
@test Element(64) == Elements.Gd
@test Element(65) == Elements.Tb
@test Element(66) == Elements.Dy
@test Element(67) == Elements.Ho
@test Element(68) == Elements.Er
@test Element(69) == Elements.Tm
@test Element(70) == Elements.Yb
@test Element(71) == Elements.Lu
@test Element(72) == Elements.Hf
@test Element(73) == Elements.Ta
@test Element(74) == Elements.W
@test Element(75) == Elements.Re
@test Element(76) == Elements.Os
@test Element(77) == Elements.Ir
@test Element(78) == Elements.Pt
@test Element(79) == Elements.Au
@test Element(80) == Elements.Hg
@test Element(81) == Elements.Tl
@test Element(82) == Elements.Pb
@test Element(83) == Elements.Bi
@test Element(84) == Elements.Po
@test Element(85) == Elements.At
@test Element(86) == Elements.Rn
@test Element(87) == Elements.Fr
@test Element(88) == Elements.Ra
@test Element(89) == Elements.Ac
@test Element(90) == Elements.Th
@test Element(91) == Elements.Pa
@test Element(92) == Elements.U
@test Element(93) == Elements.Np
@test Element(94) == Elements.Pu
@test Element(95) == Elements.Am
@test Element(96) == Elements.Cm
@test Element(97) == Elements.Bk
@test Element(98) == Elements.Cf
@test Element(99) == Elements.Es
@test Element(100) == Elements.Fm
@test Element(101) == Elements.Md
@test Element(102) == Elements.No
@test Element(103) == Elements.Lr
@test Element(104) == Elements.Rf
@test Element(105) == Elements.Db
@test Element(106) == Elements.Sg
@test Element(107) == Elements.Bh
@test Element(108) == Elements.Hs
@test Element(109) == Elements.Mt
@test Element(110) == Elements.Ds
@test Element(111) == Elements.Rg
@test Element(112) == Elements.Cn
@test Element(113) == Elements.Nh
@test Element(114) == Elements.Fl
@test Element(115) == Elements.Mc
@test Element(116) == Elements.Lv
@test Element(117) == Elements.Ts
@test Element(118) == Elements.Og
@test Element(255) == Elements.Unknown

@test_throws ArgumentError Element(-1)
@test_throws ArgumentError Element(119)

# see https://github.com/hildebrandtlab/BiochemicalAlgorithms.jl/pull/28
@test_broken parse(Elements, "MG") == Elements.Mg 
@test_broken parse(Elements, "ZN") == Elements.Zn
end
