Base.precompile(load_pdb, (String,))
Base.precompile(load_mmcif, (String,))
Base.precompile(load_hinfile, (String,))
Base.precompile(load_pubchem_json, (String,))
Base.precompile(load_sdfile, (String,))
Base.precompile(read_ball_ini_file, (String,))
Base.precompile(normalize_names!, (System{Float32}, FragmentDB{Float32}))
Base.precompile(reconstruct_fragments!, (System{Float32}, FragmentDB{Float32}))
Base.precompile(build_bonds!, (System{Float32}, FragmentDB{Float32}))
Base.precompile(AmberFF, (System{Float32},))
Base.precompile(compute_energy!, (ForceField{Float32},))
Base.precompile(compute_forces!, (ForceField{Float32},))
Base.precompile(optimize_structure!, (ForceField{Float32},))
Base.precompile(optimize_hydrogen_positions!, (ForceField{Float32},))
